### ISSUE TITLE
[문의] 2차 저작물의 라이센스 재정의 건 

### ISSUE THREAD

**Issue by roboticsware** [g34r/OpenTyping#13]
안녕하세요. 먼저, 귀하의 노력물을 많은 사람들의 공익을 위해 오픈소스로 공개해 주셔서 깊은 감사를 드립니다. 저희 또한 해당 저작물을 더 필요한 곳 특별히 개발도상국(이하 개도국)에서 잘 사용할 수 있도록  2차저작물(https://github.com/roboticsware/OpenTyping)을 만들어 재배포 하고자 합니다. 2차 저작목적은 완전한 공익 목적(학교에서 아이들의 자국어 기반 타이핑 연습)입니다.  이미 저자께서는 해당 오픈소스에 MIT 라이센스를 적용하셨기 때문에 2차 저작에 있어서나 2차 저작 후 심지어 상업 판매까지 자유가 주어진 것을 압니다. 제 계획은 이 2차 저작물 배포시 라이센스를 기존 mit 에서  gpl 재정의 배포하려고 합니다. 목적은 완전한 공익성 유지를 계속 강하게 가져가려는 이유입니다. 혹여나 개도국에서 빈번히 일어나는 저작권 무시 불법 복제 문제, 상업화 문제의 차단 이유 입니다. 인터넷 검색에서 확인한 바로  mit의 원저작물의 2차저작물의 라이센스 변경이 가능하다고 합니다.(https://www.oss.kr/oss_license_qna/show/f30bfb41-8fbf-425d-aabb-fc739b3ca0b7?page=4) 그럼에도 불구하고 원저작자님께 알려드리는게 예의라 여겨 이곳에 글을 남깁니다. 감사합니다.

**Comment by suhdonghwi** [comment]
라이센스에 명시되어있는 것처럼 라이센스 변경, 사용 등 모두 자유롭게 하시면 될 것 같습니다. 좋은 곳에 써주셔서 감사합니다.
